Repository aliencube/azure-openai-sdk-proxy, pull requests merged in 2024-08, with the labels that each got.

#191 Add `OpenAISettingsBuilder`
  .gitignore
  src/AzureOpenAIProxy.ApiApp/Builders/OpenAISettingsBuilder.cs
  src/AzureOpenAIProxy.ApiApp/Extensions/ServiceCollectionExtensions.cs
  test/AzureOpenAIProxy.ApiApp.Tests/Builders/OpenAISettingsBuilderTests.cs
Labels: ossca, backend, task

#192 Add extension method for OpenAISettingsBuilder
  src/AzureOpenAIProxy.ApiApp/Extensions/OpenAISettingsBuilderExtensions.cs
  src/AzureOpenAIProxy.ApiApp/Extensions/ServiceCollectionExtensions.cs
  test/AzureOpenAIProxy.ApiApp.Tests/Extensions/OpenAISettingsBuilderExtensionsTests.cs
Labels: ossca, backend, task

#194 Add bicep files for Key Vault
  .github/workflows/azure-dev-build-only.yml
  .github/workflows/azure-dev.yml
  README.md
  infra/abbreviations.json
  infra/aspire.bicep
  infra/aspire.parameters.json
  infra/core/security/keyvault-access.bicep
  infra/core/security/keyvault-secret.bicep
  infra/core/security/keyvault.bicep
  infra/scripts/Purge-ApiManagements.ps1
  infra/scripts/Purge-CognitiveServices.ps1
  infra/scripts/Purge-KeyVaults.ps1
Labels: ossca, apphost, task

#197 Add Key Vault client
  .github/workflows/azure-dev.yml
  src/AzureOpenAIProxy.ApiApp/AzureOpenAIProxy.ApiApp.csproj
  src/AzureOpenAIProxy.ApiApp/Configurations/AzureSettings.cs
  src/AzureOpenAIProxy.ApiApp/Configurations/KeyVaultSettings.cs
  src/AzureOpenAIProxy.ApiApp/Extensions/ServiceCollectionExtensions.cs
  src/AzureOpenAIProxy.ApiApp/Program.cs
  src/AzureOpenAIProxy.ApiApp/appsettings.Development.sample.json
  src/AzureOpenAIProxy.ApiApp/appsettings.json
  test/AzureOpenAIProxy.ApiApp.Tests/Extensions/ServiceCollectionExtensionsTests.cs
Labels: ossca, backend, task

#228 Add WithKeyVault method
  .github/workflows/azure-dev-build-only.yml
  src/AzureOpenAIProxy.ApiApp/Extensions/OpenAISettingsBuilderExtensions.cs
  src/AzureOpenAIProxy.ApiApp/Extensions/ServiceCollectionExtensions.cs
  test/AzureOpenAIProxy.ApiApp.Tests/Extensions/OpenAISettingsBuilderExtensionsTests.cs
  test/AzureOpenAIProxy.ApiApp.Tests/Extensions/ServiceCollectionExtensionsTests.cs
Labels: ossca, backend, task

#229 Add spectral rules #20
  .spectral.yaml
Labels: ossca, task, openapi

#231 [OpenAPI] Add endpoint for view event details #207
  src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEndpointUrls.cs
  src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
  src/AzureOpenAIProxy.ApiApp/Endpoints/EndpointUrls.cs
  src/AzureOpenAIProxy.ApiApp/Models/AdminEventDetails.cs
  src/AzureOpenAIProxy.ApiApp/Program.cs
  test/AzureOpenAIProxy.AppHost.Tests/ApiApp/Endpoints/AdminGetEventDetailsOpenApiTests.cs
  test/AzureOpenAIProxy.AppHost.Tests/AppHostProgramTests.cs
  test/AzureOpenAIProxy.AppHost.Tests/Fixtures/AspireAppHostFixture.cs
Labels: ossca, task, openapi

#254 Update main layout to show/hide the sidebar
  .github/workflows/azure-dev-build-only.yml
  .github/workflows/azure-dev.yml
  Directory.Build.props
  src/AzureOpenAIProxy.PlaygroundApp/Components/Layout/MainLayout.razor
  src/AzureOpenAIProxy.PlaygroundApp/Components/Layout/MainLayout.razor.cs
  test/AzureOpenAIProxy.ApiApp.Tests/UnitTest1.cs
  test/AzureOpenAIProxy.PlaygroundApp.Tests/AzureOpenAIProxy.PlaygroundApp.Tests.csproj
  test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/HomePageTests.cs
  test/AzureOpenAIProxy.PlaygroundApp.Tests/UnitTest1.cs
Labels: ossca, playground, admin, task

#258 Add test scripts to run locally
  README.md
  scripts/Run-Tests.ps1
  scripts/run-tests.sh
Labels: ossca, task, devops

#265 [OpenAPI] Add endpoint for list event details #217
  src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEndpointUrls.cs
  src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
  src/AzureOpenAIProxy.ApiApp/Filters/OpenApiTagFilter.cs
  src/AzureOpenAIProxy.ApiApp/Program.cs
  test/AzureOpenAIProxy.AppHost.Tests/ApiApp/Endpoints/AdminGetEventsOpenApiTests.cs
Labels: ossca, admin, team-kim, task, openapi

#243 [Devops] Feature/221 add openapi linting
  .github/workflows/azure-dev-build-only.yml
  .github/workflows/azure-dev.yml
Labels: ossca, team-park, task, devops

#270 [DevOps] Update test scripts
  .gitignore
  README.md
  scripts/Run-Tests.ps1
  scripts/run-tests.sh
  src/AzureOpenAIProxy.ApiApp/appsettings.json
Labels: ossca, task, devops

#242 [Admin] Component: Landing Page(Page) #235
  src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Admin.razor
  test/AzureOpenAIProxy.AppHost.Tests/PlaygroundApp/Pages/AdminPageTests.cs
Labels: ossca, admin, team-kim, task

#241 [OpenAPI] Add endpoint for update event details
  .spectral.yaml
  src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
  src/AzureOpenAIProxy.ApiApp/Program.cs
  test/AzureOpenAIProxy.AppHost.Tests/ApiApp/Endpoints/AdminUpdateEventDetailsOpenApiTests.cs
Labels: ossca, team-kim, task, openapi

#249 [Playground] Component: Page component #246
  src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Playground.razor
  test/AzureOpenAIProxy.AppHost.Tests/PlaygroundApp/Components/Pages/PlaygroundPageTest.cs
Labels: ossca, playground, team-oh, task

#259 [OpenAPI] Add endpoint for list of events #179
  src/AzureOpenAIProxy.ApiApp/Endpoints/EndpointUrls.cs
  src/AzureOpenAIProxy.ApiApp/Endpoints/EventEndpoint.cs
  src/AzureOpenAIProxy.ApiApp/Extensions/ServiceCollectionExtensions.cs
  src/AzureOpenAIProxy.ApiApp/Filters/OpenApiTagFilter.cs
  src/AzureOpenAIProxy.ApiApp/Models/AdminEventDetails.cs
  src/AzureOpenAIProxy.ApiApp/Models/EventDetails.cs
  src/AzureOpenAIProxy.ApiApp/Program.cs
  test/AzureOpenAIProxy.AppHost.Tests/ApiApp/Endpoints/GetEventsOpenApiTests.cs
Labels: ossca, team-oh, task, openapi

#261 [OpenAPI] Add endpoint for create event details #212
  src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
  src/AzureOpenAIProxy.ApiApp/Program.cs
  test/AzureOpenAIProxy.AppHost.Tests/ApiApp/Endpoints/AdminCreateEventsOpenApiTests.cs
Labels: ossca, team-oh, task, openapi

#278 Update tests to ensure apps are up and running
  Directory.Build.props
  test/AzureOpenAIProxy.AppHost.Tests/ApiApp/Endpoints/AdminCreateEventsOpenApiTests.cs
  test/AzureOpenAIProxy.AppHost.Tests/ApiApp/Endpoints/AdminGetEventDetailsOpenApiTests.cs
  test/AzureOpenAIProxy.AppHost.Tests/ApiApp/Endpoints/AdminGetEventsOpenApiTests.cs
  test/AzureOpenAIProxy.AppHost.Tests/ApiApp/Endpoints/AdminUpdateEventDetailsOpenApiTests.cs
  test/AzureOpenAIProxy.AppHost.Tests/ApiApp/Endpoints/GetEventsOpenApiTests.cs
  test/AzureOpenAIProxy.AppHost.Tests/AppHostProgramTests.cs
  test/AzureOpenAIProxy.AppHost.Tests/Fixtures/AspireAppHostFixture.cs
  test/AzureOpenAIProxy.AppHost.Tests/PlaygroundApp/Components/Pages/PlaygroundPageTest.cs
  test/AzureOpenAIProxy.AppHost.Tests/PlaygroundApp/Pages/AdminPageTests.cs
  test/AzureOpenAIProxy.AppHost.Tests/PlaygroundApp/Pages/HomePageTests.cs
Labels: ossca, devops

#244 [Playground] Component - Tab for system message and parameters (UI only) #225
  src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Home.razor
  src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Playground.razor
  src/AzureOpenAIProxy.PlaygroundApp/Components/UI/ConfigTabComponent.razor
  src/AzureOpenAIProxy.PlaygroundApp/Components/_Imports.razor
  src/AzureOpenAIProxy.PlaygroundApp/Program.cs
  test/AzureOpenAIProxy.PlaygroundApp.Tests/UI/ConfigTabComponentTest.cs
Labels: ossca, playground, team-oh, task

#274 [Backend API]Refactor OpenAPI doc version to appsettings.json
  .github/workflows/azure-dev-build-only.yml
  .github/workflows/azure-dev.yml
  src/AzureOpenAIProxy.ApiApp/Configurations/OpenApiSettings.cs
  src/AzureOpenAIProxy.ApiApp/Constants.cs
  src/AzureOpenAIProxy.ApiApp/Extensions/ApplicationBuilderExtensions.cs
  src/AzureOpenAIProxy.ApiApp/Extensions/OpenApiSettingsExtensions.cs
  src/AzureOpenAIProxy.ApiApp/Extensions/ServiceCollectionExtensions.cs
  test/AzureOpenAIProxy.ApiApp.Tests/Extensions/OpenApiSettingsExtensionsTests.cs
Labels: ossca, backend, team-park, task

#236 [Playground] Component - button to display a given input #171
  src/AzureOpenAIProxy.PlaygroundApp/Components/Layout/MainLayout.razor
  src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Tests.razor
  src/AzureOpenAIProxy.PlaygroundApp/Components/UI/DebugButtonComponent.razor
  src/AzureOpenAIProxy.PlaygroundApp/Components/UI/DebugTargetComponent.razor
  test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/TestsPageTests.cs
Labels: ossca, playground, team-park, task
